name: Generate game info posters

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: playwright install chromium
      - run: flask pdf poster
      - uses: actions/upload-artifact@v4
        with:
          name: posters
          path: output
